name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  http: ^1.2.2
  flutter_stripe: ^11.0.0
  flutter_dotenv: ^5.1.0
  mailer: ^6.1.2
  shimmer: ^3.0.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  image_picker: ^1.2.0
  firebase_storage: ^11.6.5
  gap: ^3.0.1
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/logo.png
    - assets/images/logo_dark.png

flutter_native_splash:
  color: "#2196F3"  # Blue background for light mode
  image: assets/images/logo.png

  color_dark: "#0A192F" # Dark navy for dark mode
  image_dark: assets/images/logo_dark.png

  android: true
  ios: true


  android_12:
    image: assets/images/logo.png
    icon_background_color: "#2196F3"
    image_dark: assets/images/logo_dark.png
    icon_background_color_dark: "#0A192F"
